source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LGBCategory_Example', :exclusive => true do
  pod 'LGBCategory', :path => '../'
end

target 'LGBCategory_Tests', :exclusive => true do
  pod 'LGBCategory', :path => '../'

  
end
